<a href="https://colab.research.google.com/github/gpancardo/manipulacionDatos/blob/main/cursoNumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso Numpy y Pandas
![image.png](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmiro.medium.com%2Fmax%2F2400%2F0*yoWcWha-rTtORck4.png&f=1&nofb=1&ipt=3b46a0b6ae9f1dc26155a6d83b50c905b6264c5fe4d515a0733344f2f632b00c&ipo=images)

## Numpy

###Arrays y Matrices

Vamos a crear una lista y convertirla en un array de numpy

In [ ]:
import numpy as np
lista=[1,2,3,4,5,6,7,8,9,0]
lista=np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

Podemos crear matrices de varias dimensiones con numpy

In [ ]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ahora vamos a hacer un indexado para poder trabajar con cualquier elemento. Vamos a tomar uno de la lista y otro de la matriz

In [ ]:
print(lista[1])
print(matriz[0,0])

2
1


###Slicing

Vamos a hacer slicing, esto es para pedir un rango de valores

In [ ]:
print(lista[0:5])
print(matriz[1:,0:])

[1, 2, 3, 4, 5]
[[4 5 6]
 [7 8 9]]


Se pueden pedir rangos sin el inicio o fin para tener los mayores a X o menores a X

In [ ]:
print(matriz[1,1:])
print(lista[2:])

print(lista[:3])

[[5 6]
 [8 9]]
[3, 4, 5, 6, 7, 8, 9, 0]
[1, 2, 3]


También se puede pedir que sean de dos en dos, tres en tres, etc

In [ ]:
print(lista[::2])

[1, 3, 5, 7, 9]


###Cambiar tipo de dato de matrices

Se pueden cambiar de tipo de dato los elementos del array

In [ ]:
nuevaLista=np.array(lista)
nuevaLista=nuevaLista.astype(np.float64)
print(nuevaLista)
nuevaLista=nuevaLista.astype(np.string_)
print(nuevaLista)

[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
[b'1.0' b'2.0' b'3.0' b'4.0' b'5.0' b'6.0' b'7.0' b'8.0' b'9.0' b'0.0']


###Generar matrices con instrucciones

Podemos crear arrays con rangos de valores con arrange


In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

O arreglos llenos de ceros con zeros

In [ ]:
ceros=np.zeros(4)
ceros=ceros.astype(np.int16)
print(ceros)

[0 0 0 0]


Se puede hacer lo mismo con una matriz. Esto se usa para definir la base de una que sea llenada a futuro.

In [ ]:
matrixCeros=np.zeros((5,5))
print(matrixCeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Hay una función muy similar, pero que llena la matriz con unos

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Se puede crear un espacio lineal con linspace. Así generamos un número C de cantidades entre A y B en orden.

In [ ]:
np.linspace(0,10,55)

array([ 0.        ,  0.18518519,  0.37037037,  0.55555556,  0.74074074,
        0.92592593,  1.11111111,  1.2962963 ,  1.48148148,  1.66666667,
        1.85185185,  2.03703704,  2.22222222,  2.40740741,  2.59259259,
        2.77777778,  2.96296296,  3.14814815,  3.33333333,  3.51851852,
        3.7037037 ,  3.88888889,  4.07407407,  4.25925926,  4.44444444,
        4.62962963,  4.81481481,  5.        ,  5.18518519,  5.37037037,
        5.55555556,  5.74074074,  5.92592593,  6.11111111,  6.2962963 ,
        6.48148148,  6.66666667,  6.85185185,  7.03703704,  7.22222222,
        7.40740741,  7.59259259,  7.77777778,  7.96296296,  8.14814815,
        8.33333333,  8.51851852,  8.7037037 ,  8.88888889,  9.07407407,
        9.25925926,  9.44444444,  9.62962963,  9.81481481, 10.        ])

La función eye crea matrices diagonales

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###Funciones básicas en Numpy

Las funciones max y min sirven para encontrar el elemento mayor o menor de una matriz. Se le puede dar un argumento para cambiar el eje en el que se mide mayor o menor (por ejemplo, cero nos da el mayor de cada columna).

In [ ]:
import numpy as np
arregloPrueba=[[1,2,3],[4,5,6],[7,8,9]]
arregloPrueba=np.array(arregloPrueba)
print(arregloPrueba.max())
print(arregloPrueba.min())
print(arregloPrueba.max(0))

9
1
[7 8 9]


argmax y argmin nos dan el índice de esos elementos

In [ ]:
print(arregloPrueba.max(0))
print(arregloPrueba.min(0))

[7 8 9]
[1 2 3]


ptp es Peak to Peak, habla del medio entre los puntos menor y mayor del array

In [ ]:
print(arregloPrueba.ptp())

9
1
8


Percentile nos da el equivalente al porcentaje que indiquemos dentro del arreglo.

In [ ]:
import numpy as np
arregloPrueba=[[1,2,3],[4,5,6],[7,8,9]]
arregloPrueba=np.array(arregloPrueba)
print(np.percentile(arregloPrueba,50))
print(np.percentile(arregloPrueba,100))

5.0
9.0


sort sirve para ordenar de mayor a menor los elementos

median es igual al percentile 50. Es la mediana de los elementos del arreglo

In [ ]:
np.median(arregloPrueba)

5.0

std es la desviación estandar de los elementos

In [ ]:
np.std(arregloPrueba)

2.581988897471611

var es la varianza

In [ ]:
print(np.std(arregloPrueba)**2)
print(np.var(arregloPrueba))

6.666666666666666
6.666666666666667


mean es la media

In [ ]:
np.mean(arregloPrueba)

5.0

concatenate concatena elementos por un eje

In [ ]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


ndim nos da las dimensiones de una matriz

In [ ]:
a=np.array(a)
a.ndim

2

si se da a un argumento un .T se transpone la matriz

In [ ]:
a=np.array(a)
b=np.array(b)
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
